/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphic_woc;

import usuario.UserInfo;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logic.Loader;
import logic.Match;
import logic.User;
import woc.Building;
import woc.Soldier;

/**
 *
 * @author Felipe
 */
public class ConfigurationFrame extends javax.swing.JFrame {
    
    private static UserInfo information;
    private int tipo;
    
    /**
     * Creates new form ConfigurationFrame
     */
    public ConfigurationFrame() {
        initComponents();
        lblUsuario.setText(information.getUsuario());
        btnJugar.setVisible(false);
        pnlAdministracion.setVisible(false);
    }

    public static void initUser(UserInfo user) {
        information = user;
    }
    
    private void limpiarUsuarios() {
        txtNombre.setText("");
        txtContrasena.setText("");
        cmbTipo.setSelectedIndex(-1);
    }
    
    private void limpiarSoldados() {
        cmbTipoSoldado.setSelectedIndex(-1);
        lblFotoSoldado.setIcon(null);
        txtNombreSoldado.setText("");
        spnVida.setValue(1);
        spnEspacio.setValue(1);
        spnAtaque.setValue(1);
        spnVelocidad.setValue(1);
        spnNivel.setValue(1);
        spnJugadorSoldado.setValue(1);
        spnCosto.setValue(1);
    }
    
    private void limpiarObstaculos() {
        cmbTipoObstaculo.setSelectedIndex(-1);
        lblFotoObstaculo.setIcon(null);
        txtNombreObstaculo.setText("");
        spnVida.setValue(1);
        spnNivel.setValue(1);
        spnlJugadorObstaculo.setValue(1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInformacion = new javax.swing.JPanel();
        btnPartida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPartidas = new javax.swing.JList();
        lblUsuario = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        pnlOperacion = new javax.swing.JPanel();
        tbpModulos = new javax.swing.JTabbedPane();
        pnlJuego = new javax.swing.JPanel();
        pnlIniciar = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        pnlOpciones = new javax.swing.JPanel();
        tbpGame = new javax.swing.JTabbedPane();
        pnlSoldados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSoldados = new javax.swing.JList();
        pnlSoldadosInformacion = new javax.swing.JPanel();
        lblNombreSoldado = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblEspacio = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        lblTipoSoldado = new javax.swing.JLabel();
        txtNombreSoldado = new javax.swing.JTextField();
        spnVida = new javax.swing.JSpinner();
        spnEspacio = new javax.swing.JSpinner();
        spnAtaque = new javax.swing.JSpinner();
        pnlFotoSoldado = new javax.swing.JPanel();
        lblFotoSoldado = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();
        spnVelocidad = new javax.swing.JSpinner();
        cmbTipoSoldado = new javax.swing.JComboBox();
        lblNivel = new javax.swing.JLabel();
        spnNivel = new javax.swing.JSpinner();
        lblJugadorSoldado = new javax.swing.JLabel();
        spnJugadorSoldado = new javax.swing.JSpinner();
        lblCosto = new javax.swing.JLabel();
        spnCosto = new javax.swing.JSpinner();
        pnlEstructuras = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstEstructuras = new javax.swing.JList();
        pnlEstructurasInformacion = new javax.swing.JPanel();
        lblNombreObstaculo = new javax.swing.JLabel();
        lblVidaObstaculo = new javax.swing.JLabel();
        lblNivelObstaculo = new javax.swing.JLabel();
        pnlFotoObstaculo = new javax.swing.JPanel();
        lblFotoObstaculo = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        cmbTipoObstaculo = new javax.swing.JComboBox();
        lblTipoObstaculo = new javax.swing.JLabel();
        txtNombreObstaculo = new javax.swing.JTextField();
        spnVidaObstaculo = new javax.swing.JSpinner();
        spnNivelObstaculo = new javax.swing.JSpinner();
        lblEspacioObstaculo = new javax.swing.JLabel();
        spnEspacioObstaculo = new javax.swing.JSpinner();
        lblJugadorObstaculo = new javax.swing.JLabel();
        spnlJugadorObstaculo = new javax.swing.JSpinner();
        pnlUsuarios = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        lblTipo = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JList();
        pnlAdministracion = new javax.swing.JPanel();
        pnlCambios = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlAcciones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuraciones");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        pnlInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 22))); // NOI18N
        pnlInformacion.setMinimumSize(new java.awt.Dimension(200, 150));
        pnlInformacion.setPreferredSize(new java.awt.Dimension(300, 275));

        btnPartida.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        btnPartida.setText("Nueva partida");
        btnPartida.setMaximumSize(new java.awt.Dimension(100, 75));
        btnPartida.setMinimumSize(new java.awt.Dimension(100, 50));
        btnPartida.setPreferredSize(new java.awt.Dimension(150, 50));
        btnPartida.setRequestFocusEnabled(false);
        btnPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidaActionPerformed(evt);
            }
        });

        lstPartidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lstPartidas.setModel(new javax.swing.AbstractListModel<InGameFrame>() {
            ArrayList<InGameFrame> plays = information.getGames();
            public int getSize() { return plays.size(); }
            public InGameFrame getElementAt(int i) { return plays.get(i); }
        });
        lstPartidas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lstPartidas.setMinimumSize(new java.awt.Dimension(250, 500));
        lstPartidas.setPreferredSize(new java.awt.Dimension(300, 0));
        lstPartidas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPartidasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPartidas);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblUsuario.setText("Usuario");
        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Bienvenido"));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("Salir");

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionLayout.createSequentialGroup()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlOperacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuraciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 22))); // NOI18N

        tbpModulos.setMinimumSize(new java.awt.Dimension(800, 500));
        tbpModulos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbpModulosStateChanged(evt);
            }
        });

        pnlIniciar.setPreferredSize(new java.awt.Dimension(200, 170));
        pnlIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlIniciarMouseExited(evt);
            }
        });

        btnJugar.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJugarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlIniciarLayout = new javax.swing.GroupLayout(pnlIniciar);
        pnlIniciar.setLayout(pnlIniciarLayout);
        pnlIniciarLayout.setHorizontalGroup(
            pnlIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIniciarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnJugar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlIniciarLayout.setVerticalGroup(
            pnlIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIniciarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnJugar)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlJuegoLayout = new javax.swing.GroupLayout(pnlJuego);
        pnlJuego.setLayout(pnlJuegoLayout);
        pnlJuegoLayout.setHorizontalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJuegoLayout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(pnlIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        pnlJuegoLayout.setVerticalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJuegoLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(pnlIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );

        tbpModulos.addTab("Partida", pnlJuego);

        lstSoldados.setModel(new javax.swing.AbstractListModel<Soldier>() {
            ArrayList<Soldier> army = Loader.getManager().getSoldiers();
            public int getSize() { return army.size(); }
            public Soldier getElementAt(int i) { return army.get(i); }
        });
        lstSoldados.setMinimumSize(new java.awt.Dimension(300, 0));
        lstSoldados.setPreferredSize(new java.awt.Dimension(350, 0));
        lstSoldados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstSoldadosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstSoldados);

        pnlSoldadosInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        lblNombreSoldado.setText("Nombre");

        lblVida.setText("Vida");

        lblEspacio.setText("Espacio");

        lblAtaque.setText("Ataque");

        lblVelocidad.setText("Velocidad");

        lblTipoSoldado.setText("Tipo");

        spnVida.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        spnEspacio.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        spnAtaque.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        lblFotoSoldado.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        btnAbrir.setText("Abrir");
        btnAbrir.setEnabled(false);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFotoSoldadoLayout = new javax.swing.GroupLayout(pnlFotoSoldado);
        pnlFotoSoldado.setLayout(pnlFotoSoldadoLayout);
        pnlFotoSoldadoLayout.setHorizontalGroup(
            pnlFotoSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoSoldadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbrir)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pnlFotoSoldadoLayout.setVerticalGroup(
            pnlFotoSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoSoldadoLayout.createSequentialGroup()
                .addGroup(pnlFotoSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFotoSoldadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFotoSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFotoSoldadoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAbrir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spnVelocidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        cmbTipoSoldado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contacto", "Medio alcance", "Aereo", "Grandes", "Heroes" }));
        cmbTipoSoldado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoSoldadoItemStateChanged(evt);
            }
        });

        lblNivel.setText("Nivel");

        spnNivel.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        lblJugadorSoldado.setText("Nivel Jugador");

        spnJugadorSoldado.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        lblCosto.setText("Costo");

        spnCosto.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout pnlSoldadosInformacionLayout = new javax.swing.GroupLayout(pnlSoldadosInformacion);
        pnlSoldadosInformacion.setLayout(pnlSoldadosInformacionLayout);
        pnlSoldadosInformacionLayout.setHorizontalGroup(
            pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoldadosInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFotoSoldado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSoldadosInformacionLayout.createSequentialGroup()
                        .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSoldadosInformacionLayout.createSequentialGroup()
                                .addComponent(lblTipoSoldado)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTipoSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSoldadosInformacionLayout.createSequentialGroup()
                                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreSoldado)
                                    .addComponent(lblVida)
                                    .addComponent(lblEspacio)
                                    .addComponent(lblAtaque)
                                    .addComponent(lblVelocidad)
                                    .addComponent(lblNivel)
                                    .addComponent(lblJugadorSoldado)
                                    .addComponent(lblCosto))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnVida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(spnCosto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spnJugadorSoldado, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spnNivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSoldadosInformacionLayout.setVerticalGroup(
            pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSoldadosInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoSoldado)
                    .addComponent(cmbTipoSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFotoSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreSoldado)
                    .addComponent(txtNombreSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVida)
                    .addComponent(spnVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspacio)
                    .addComponent(spnEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtaque)
                    .addComponent(spnAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidad)
                    .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel)
                    .addComponent(spnNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadorSoldado)
                    .addComponent(spnJugadorSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSoldadosInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCosto)
                    .addComponent(spnCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        cmbTipoSoldado.setSelectedIndex(-1);

        javax.swing.GroupLayout pnlSoldadosLayout = new javax.swing.GroupLayout(pnlSoldados);
        pnlSoldados.setLayout(pnlSoldadosLayout);
        pnlSoldadosLayout.setHorizontalGroup(
            pnlSoldadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoldadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSoldadosInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSoldadosLayout.setVerticalGroup(
            pnlSoldadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoldadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSoldadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(pnlSoldadosInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbpGame.addTab("Soldados", pnlSoldados);

        lstEstructuras.setModel(new javax.swing.AbstractListModel<Building>() {
            ArrayList<Building> obstacles = Loader.getManager().getBuildings();
            public int getSize() { return obstacles.size(); }
            public Building getElementAt(int i) { return obstacles.get(i); }
        });
        lstEstructuras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEstructuras.setMaximumSize(new java.awt.Dimension(300, 0));
        lstEstructuras.setPreferredSize(new java.awt.Dimension(350, 0));
        lstEstructuras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEstructurasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstEstructuras);

        pnlEstructurasInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        lblNombreObstaculo.setText("Nombre");

        lblVidaObstaculo.setText("Vida");

        lblNivelObstaculo.setText("Nivel");

        lblFotoObstaculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setEnabled(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFotoObstaculoLayout = new javax.swing.GroupLayout(pnlFotoObstaculo);
        pnlFotoObstaculo.setLayout(pnlFotoObstaculoLayout);
        pnlFotoObstaculoLayout.setHorizontalGroup(
            pnlFotoObstaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoObstaculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFotoObstaculoLayout.setVerticalGroup(
            pnlFotoObstaculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoObstaculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFotoObstaculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar)
                .addGap(35, 35, 35))
        );

        cmbTipoObstaculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muro", "Torre", "Canon", "Bomba" }));
        cmbTipoObstaculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoObstaculoItemStateChanged(evt);
            }
        });

        lblTipoObstaculo.setText("Tipo");

        spnVidaObstaculo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        spnNivelObstaculo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        lblEspacioObstaculo.setText("Espacio");

        spnEspacioObstaculo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        lblJugadorObstaculo.setText("Nivel Jugador");

        javax.swing.GroupLayout pnlEstructurasInformacionLayout = new javax.swing.GroupLayout(pnlEstructurasInformacion);
        pnlEstructurasInformacion.setLayout(pnlEstructurasInformacionLayout);
        pnlEstructurasInformacionLayout.setHorizontalGroup(
            pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstructurasInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstructurasInformacionLayout.createSequentialGroup()
                        .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspacioObstaculo)
                            .addComponent(lblNivelObstaculo))
                        .addGap(47, 47, 47)
                        .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnNivelObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnEspacioObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(281, 281, 281))
                    .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEstructurasInformacionLayout.createSequentialGroup()
                            .addComponent(lblTipoObstaculo)
                            .addGap(18, 18, 18)
                            .addComponent(cmbTipoObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlEstructurasInformacionLayout.createSequentialGroup()
                            .addComponent(lblJugadorObstaculo)
                            .addGap(18, 18, 18)
                            .addComponent(spnlJugadorObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlEstructurasInformacionLayout.createSequentialGroup()
                            .addComponent(pnlFotoObstaculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(pnlEstructurasInformacionLayout.createSequentialGroup()
                            .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreObstaculo)
                                .addComponent(lblVidaObstaculo))
                            .addGap(46, 46, 46)
                            .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spnVidaObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        pnlEstructurasInformacionLayout.setVerticalGroup(
            pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstructurasInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoObstaculo)
                    .addComponent(cmbTipoObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFotoObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreObstaculo)
                    .addComponent(txtNombreObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVidaObstaculo)
                    .addComponent(spnVidaObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspacioObstaculo)
                    .addComponent(spnEspacioObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelObstaculo)
                    .addComponent(spnNivelObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEstructurasInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadorObstaculo)
                    .addComponent(spnlJugadorObstaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbTipoObstaculo.setSelectedIndex(-1);

        javax.swing.GroupLayout pnlEstructurasLayout = new javax.swing.GroupLayout(pnlEstructuras);
        pnlEstructuras.setLayout(pnlEstructurasLayout);
        pnlEstructurasLayout.setHorizontalGroup(
            pnlEstructurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstructurasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEstructurasInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEstructurasLayout.setVerticalGroup(
            pnlEstructurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstructurasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstructurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(pnlEstructurasInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbpGame.addTab("Estructuras", pnlEstructuras);

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpGame)
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpGame)
                .addContainerGap())
        );

        tbpModulos.addTab("Opciones", pnlOpciones);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        lblNombre.setText("Nombre");

        lblContrasena.setText("Contrasena");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Jugador" }));

        lblTipo.setText("Tipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContrasena)
                    .addComponent(lblNombre)
                    .addComponent(lblTipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        cmbTipo.setSelectedIndex(-1);

        lstUsuarios.setModel(new javax.swing.AbstractListModel<UserInfo>() {
            ArrayList<UserInfo> players = User.getManager().find("");
            public int getSize() { return players.size(); }
            public UserInfo getElementAt(int i) { return players.get(i); }
        });
        lstUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstUsuarios.setMinimumSize(new java.awt.Dimension(300, 0));
        lstUsuarios.setPreferredSize(new java.awt.Dimension(350, 0));
        lstUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsuariosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstUsuarios);

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );

        tbpModulos.addTab("Usuarios", pnlUsuarios);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCambiosLayout = new javax.swing.GroupLayout(pnlCambios);
        pnlCambios.setLayout(pnlCambiosLayout);
        pnlCambiosLayout.setHorizontalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        pnlCambiosLayout.setVerticalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCambiosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)))
        );

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)))
        );

        javax.swing.GroupLayout pnlAdministracionLayout = new javax.swing.GroupLayout(pnlAdministracion);
        pnlAdministracion.setLayout(pnlAdministracionLayout);
        pnlAdministracionLayout.setHorizontalGroup(
            pnlAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdministracionLayout.createSequentialGroup()
                .addComponent(pnlAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(193, 193, 193)
                .addComponent(pnlCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAdministracionLayout.setVerticalGroup(
            pnlAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAdministracionLayout.createSequentialGroup()
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlOperacionLayout = new javax.swing.GroupLayout(pnlOperacion);
        pnlOperacion.setLayout(pnlOperacionLayout);
        pnlOperacionLayout.setHorizontalGroup(
            pnlOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdministracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbpModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOperacionLayout.setVerticalGroup(
            pnlOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidaActionPerformed
        String play = JOptionPane.showInputDialog(this, "Ingrese un identificador para la partida", "Partida", JOptionPane.INFORMATION_MESSAGE);
        if (!play.equals("")) {
            Match.getManager().insert(play + "," + information.getIdUsuario());
        }
    }//GEN-LAST:event_btnPartidaActionPerformed

    private void lstPartidasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPartidasValueChanged
        InGameFrame game = (InGameFrame) lstPartidas.getSelectedValue();
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_lstPartidasValueChanged

    private void lstUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsuariosValueChanged
        UserInfo player = (UserInfo) lstUsuarios.getSelectedValue();
        txtNombre.setText(player.getUsuario());
        txtContrasena.setText(player.getContrasena());
        cmbTipo.setSelectedItem(player.getTipo());
        btnEliminar.setEnabled(true);
        tipo = 1;
    }//GEN-LAST:event_lstUsuariosValueChanged

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String data = "";
        if (tipo == 0) {
            if (tbpModulos.getSelectedIndex() == 2) {
                data = txtNombre.getText() + "," + txtContrasena.getText() + "," + cmbTipo.getSelectedItem();
                if (data.split(",").length == 3) {
                    User.getManager().insert(data);
                }
            } else {
                if (tbpGame.getSelectedIndex() == 0) {
                    if (cmbTipoSoldado.getSelectedIndex() > -1 && lblFotoSoldado.getIcon() != null && !txtNombreSoldado.getText().equals("")) {
                        Soldier character = null;
                    }
                } else {
                    if (cmbTipoObstaculo.getSelectedIndex() > - 1 && lblFotoObstaculo.getIcon() != null && !txtNombreObstaculo.getText().equals("")) {
                        Building place = new Building();
                        place.setName(txtNombreObstaculo.getText());
                        place.setMaxHP(Integer.parseInt(spnVidaObstaculo.getValue().toString()));
                    }
                }
            }
        } else {
            if (tbpModulos.getSelectedIndex() == 2) {
                data = "nombre = " + txtNombre.getText() + ", contrasena = " + txtContrasena.getText() + ", tipo = " + cmbTipo.getSelectedItem();
                UserInfo player = (UserInfo) lstUsuarios.getSelectedValue();
                User.getManager().edit(data, "idUsuario = " + player.getIdUsuario());
            } else {
                if (tbpGame.getSelectedIndex() == 0) {
                    Soldier character = (Soldier) lstSoldados.getSelectedValue();
                    character.setName(txtNombreSoldado.getText());
                    Loader.getManager().saveSoldiers();
                } else {
                    Building place = (Building) lstEstructuras.getSelectedValue();
                    Loader.getManager().saveBuildings();
                }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (tbpModulos.getSelectedIndex() == 2) {
            limpiarUsuarios();
        } else {
            if (tbpGame.getSelectedIndex() == 0) {
                limpiarSoldados();
            } else {
                limpiarObstaculos();
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        tipo = 0;
        if (tbpModulos.getSelectedIndex() == 2) {
            limpiarUsuarios();
        } else {
            if (tbpGame.getSelectedIndex() == 0) {
                limpiarSoldados();
            } else {
                limpiarObstaculos();
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tbpModulos.getSelectedIndex() == 2) {
            UserInfo player = (UserInfo) lstUsuarios.getSelectedValue();
            User.getManager().remove("idUsuario = " + player.getIdUsuario());
            limpiarUsuarios();
        } else {
            if (tbpGame.getSelectedIndex() == 0) {
                Soldier character = (Soldier) lstSoldados.getSelectedValue();
                Loader.getManager().getSoldiers().remove(character);
                Loader.getManager().saveSoldiers();
                limpiarSoldados();
            } else {
                Building place = (Building) lstEstructuras.getSelectedValue();
                Loader.getManager().getBuildings().remove(place);
                Loader.getManager().saveBuildings();
                limpiarObstaculos();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbTipoSoldadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoSoldadoItemStateChanged
        if (cmbTipoSoldado.getSelectedIndex() > -1) {
            btnAbrir.setEnabled(true);
        } else {
            Loader.getManager().setElements(null);
            lblFotoSoldado.setIcon(null);
        }
    }//GEN-LAST:event_cmbTipoSoldadoItemStateChanged

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        javax.swing.JFileChooser explorer = new javax.swing.JFileChooser();
        explorer.showOpenDialog(this);
        if (!Loader.getManager().loadImages(explorer.getSelectedFiles(), 24, 24)) {
            JOptionPane.showMessageDialog(this, "Las imagenes tienen que tener un ancho y largo menor que 24", "Problema", JOptionPane.ERROR_MESSAGE);
        }
        lblFotoSoldado.setIcon(new ImageIcon(Loader.getManager().getElements()[0]));
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void lstSoldadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstSoldadosValueChanged
        Soldier element = (Soldier) lstSoldados.getSelectedValue();
        cmbTipoSoldado.setSelectedItem(element.getName());
        lblFotoSoldado.setIcon(new ImageIcon(element.getFrames()[0]));
        txtNombre.setText(element.getName());
        spnVida.setValue(element.getHP());
        spnEspacio.setValue(element.getSize());
        spnNivel.setValue(element.getLevel());
        btnEliminar.setEnabled(true);
        tipo = 1;
    }//GEN-LAST:event_lstSoldadosValueChanged

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        javax.swing.JFileChooser explorer = new javax.swing.JFileChooser();
        explorer.showOpenDialog(this);
        lblFotoObstaculo.setIcon(new ImageIcon(Loader.getManager().loadImage(explorer.getSelectedFile(), 48, 48)));
        if (lblFotoObstaculo.getIcon() == null) {
            JOptionPane.showMessageDialog(this, "Las imagenes tienen que tener un ancho y largo menor que 48", "Problema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void cmbTipoObstaculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoObstaculoItemStateChanged
        if (cmbTipoObstaculo.getSelectedIndex() > -1) {
            btnSeleccionar.setEnabled(true);
        } else {
            lblFotoObstaculo.setIcon(null);
        }
    }//GEN-LAST:event_cmbTipoObstaculoItemStateChanged

    private void lstEstructurasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEstructurasValueChanged
        Building element = (Building) lstEstructuras.getSelectedValue();
        cmbTipoObstaculo.setSelectedItem(element);
        lblFotoObstaculo.setIcon(null);
        txtNombre.setText(element.getName());
        spnVida.setValue(element.getHP());
        spnNivel.setValue(1);
        btnEliminar.setEnabled(true);
        tipo = 1;
    }//GEN-LAST:event_lstEstructurasValueChanged

    private void pnlIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIniciarMouseEntered
        btnJugar.setVisible(true);
    }//GEN-LAST:event_pnlIniciarMouseEntered

    private void pnlIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIniciarMouseExited
        btnJugar.setVisible(false);
    }//GEN-LAST:event_pnlIniciarMouseExited

    private void btnJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJugarMouseEntered
        btnJugar.setVisible(true);
    }//GEN-LAST:event_btnJugarMouseEntered

    private void tbpModulosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbpModulosStateChanged
        if (tbpModulos.getSelectedIndex() == 1 || tbpModulos.getSelectedIndex() == 2) {
            pnlAdministracion.setVisible(true);
        } else {
            pnlAdministracion.setVisible(false);
        }
    }//GEN-LAST:event_tbpModulosStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigurationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JComboBox cmbTipoObstaculo;
    private javax.swing.JComboBox cmbTipoSoldado;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblEspacio;
    private javax.swing.JLabel lblEspacioObstaculo;
    private javax.swing.JLabel lblFotoObstaculo;
    private javax.swing.JLabel lblFotoSoldado;
    private javax.swing.JLabel lblJugadorObstaculo;
    private javax.swing.JLabel lblJugadorSoldado;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivelObstaculo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreObstaculo;
    private javax.swing.JLabel lblNombreSoldado;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoObstaculo;
    private javax.swing.JLabel lblTipoSoldado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JLabel lblVida;
    private javax.swing.JLabel lblVidaObstaculo;
    private javax.swing.JList lstEstructuras;
    private javax.swing.JList lstPartidas;
    private javax.swing.JList lstSoldados;
    private javax.swing.JList lstUsuarios;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlAdministracion;
    private javax.swing.JPanel pnlCambios;
    private javax.swing.JPanel pnlEstructuras;
    private javax.swing.JPanel pnlEstructurasInformacion;
    private javax.swing.JPanel pnlFotoObstaculo;
    private javax.swing.JPanel pnlFotoSoldado;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlIniciar;
    private javax.swing.JPanel pnlJuego;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlOperacion;
    private javax.swing.JPanel pnlSoldados;
    private javax.swing.JPanel pnlSoldadosInformacion;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JSpinner spnAtaque;
    private javax.swing.JSpinner spnCosto;
    private javax.swing.JSpinner spnEspacio;
    private javax.swing.JSpinner spnEspacioObstaculo;
    private javax.swing.JSpinner spnJugadorSoldado;
    private javax.swing.JSpinner spnNivel;
    private javax.swing.JSpinner spnNivelObstaculo;
    private javax.swing.JSpinner spnVelocidad;
    private javax.swing.JSpinner spnVida;
    private javax.swing.JSpinner spnVidaObstaculo;
    private javax.swing.JSpinner spnlJugadorObstaculo;
    private javax.swing.JTabbedPane tbpGame;
    private javax.swing.JTabbedPane tbpModulos;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreObstaculo;
    private javax.swing.JTextField txtNombreSoldado;
    // End of variables declaration//GEN-END:variables
}
